# -*- coding: utf-8 -*-
"""Final Project Poem

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1dX7e5VDsDkr_Go9GlTQbMDyOUOiBC11-
"""

import random

day = ["year","hour","second","minute","dawn","evening"]
day2 = ["Easter","Hanukkah","Easter","Black Friday","my birthday","Mothers Day","Fathers Day","Monday","Friday"]
house = ["boathouse","firehouse"]
creature = ["demon","angel","fairy","Walmart employee"]
creature2 = ["blouse;","spouse;","a tiny, tiny, tiny mouse;"]
stockings = ["human skulls","socks","poptarts","bluetooth speakers","expired milk jugs","rotting leftover turkey from Thanksgiving"]
chimney = ["trashcan","sink","toilet","VCR","KFC deep fryer"]
care = ["hair,","auclair,","despair,","flair,"]
Santa = ["Jesus","the cute pizza delievery boy","my estranged uncle","a guy named Jeff","my annoying little cousin","the Walmart employee","my boss","Vishnu"]
there = ["scared,","impaired,","repaired,"]
children = ["Target employees", "little devils that they are","cute little bunnies"]
beds = ["shed,","boats made of lead,","sled,","very comfy beds," ]
sugarplums = ["disaster","the apocalypse","their imminent demise","the far flung future","fortune"]
heads = ["bread,","thread,","very heavy heads,"]
kerchief = ["book","druken rage","car","cozy couch","hot tub"]
cap = ["map,","cap,"]
L = ["short ","long ","eternal ","30 minute long "]
nap = ["rap,","trap,"]

lawn = ["edge of a cliff","lawn","patio","porch","balcony"]
clatter = ["loud pitter-patter,","clatter,","splatter,","big explosion made of antimatter,"]
sprang = ["leaped","vaulted","sprung forth","emerged","crawled out","rolled out"]
window = ["castle","Chipolte","Toys R Us","Walmart","kitchen"]
flash = ["bird,","discarded curd,","anxious nerd,","stampeding herd,"]
tore = ["Ripped","Forced","Used my big muscles to","Asked my dad to","I lazily went to","I reluctantly went to"]
sash = ["a naughty word.","a pot full of food that was recentlly stirred.","a book whose words were quite blurred.","a whisper that went unheard."]

moon = ["mid-day sun","setting sun","rising sun","blistering sun","twighlight moon","full moon"]
newfallen = ["fresh","17-day old"]
midday = ["a new pair of shoes","a wedding dress fit for a princess","the full moon at midnight"]
below = ["embargoed,","that gave off an unearthly glow,","that made me go 'whoa',"] 
eyes = ["feet","hands","socks","hat","hamsters"]
appear = ["lear","lean back in fear","all but disappear"]
sleigh = ["horse","wooden house","boat","cake"]
reindeer = ["souvenirs","mutineers","peers"]

driver = ["grandma","grandpa","decaying mummy","Mario from Super Mario 64","Bowser","Princess Peach","Yoshi"]
lively = ["unhinged","unaware","bloated","disheveled"]
quick = ["slick","non-stick","a real prick",]
in_a_moment = ["way too late that","after the fact that","instantlly"]
Nick = ["Prick","Ostpolitik"]
eagles = ["mice","rodents","black widow spiders","several rabbits tied together","a kid who ate all of his Halloween candy in one day"]
came = ["brought shame","were of great acclaim","were to blame","brought their own games","proclaimed"]
whistled = ["hollered","screeched","yodeled"]
by_name = ["mean names","weird names"]

Dasher = ["Blinko","Stinko","Potato-Masher","Prom-Queen-Disaster"]
Dancer = ["Bargin-Bin","Freddy Fazbear","Strawberry Poptart","Blues-Clues","Clifford-The-Big-Red-Reindeer"]
porch = ["the 7-11 store","the local Homedepot","my Exs house","the Misty Mountains", "Helms-Deep","Mt. Doom"]
wall = ["local mall","sprawl"]
dash_away = ["flee for your lives","fly away","get on your way with delay","get going"]

fly = ["dry","sigh","give up and cry","fall nearby","get seen by my eyes"]
an_obstacle = ["the elementary school principal","the shopping mall security guard","that highschool bully who just won't leave you alone"]
sky = ["the starry sky","the resupply","Shanghai"]
coursers = ["robbers","mailmen","entire staff of your local Walmart","flock of geese"]
flew = ["drew","knew","stewed","flew"]
toys = ["broken glass and needles","way too many beer bottles","500 copies of Halo Reach for Xbox 360"]



line_1 = "Twas the " + random.choice(day) + " before " + random.choice(day2) + ", when all through the " + random.choice(house)
line_2 = "Not a " + random.choice(creature) + " was stirring, not even a " + random.choice(creature2)
line_3 = "The " + random.choice(stockings) + " were hung by the " + random.choice(chimney) + " with " + random.choice(care)
line_4 = "In hopes that " + random.choice(Santa) + " soon would be " + random.choice(there)
line_5 = "The " + random.choice(children) + " were nestled all snug in their " + random.choice(beds)
line_6 = "While visions of " + random.choice(sugarplums) + " danced in their " + random.choice(heads)
line_7 = "And mamma in her " + random.choice(kerchief) + ", and I in my " + random.choice(cap)
line_8 = "Had just settled down for a " + random.choice(L) + random.choice(nap)

line_9 = "When out on the " + random.choice(lawn) + " there arose such a " + random.choice(clatter)
line_10 = "I " + random.choice(sprang) + " from the bed to see what was the matter."
line_11 = "Away to the " + random.choice(window) + ", I flew like a " + random.choice(flash)
line_12 = random.choice(tore) + " open the shutters and threw up " + random.choice(sash)

line_13 = "The " + random.choice(moon) + " on the breast of the " + random.choice(newfallen) + " snow"
line_14 = "Gave the lustre of " + random.choice(midday) + " to objects " + random.choice(below)
line_15 = "When what to my wondering " + random.choice(eyes) + " should " + random.choice(appear) + ","
line_16 = "But a miniture " + random.choice(sleigh) + " and eight tiny " + random.choice(reindeer) + ","

line_17 = "With a little old " + random.choice(driver) + " so " + random.choice(lively) + " and " + random.choice(quick) + ","
line_18 = "I knew " + random.choice(in_a_moment) + " it must be St. " + random.choice(Nick) + "."
line_19 = "More rapid than " + random.choice(eagles) + " his coursers they " + random.choice(came) + ","
line_20 = "And he " + random.choice(whistled) + ", and shouted, and called them " + random.choice(by_name) + ";"

line_21 = "'Now " + random.choice(Dasher) + "! Now, " + random.choice(Dancer) + "! Now, Prancer And former US President Nixon!"
line_22 = "On, Comet! On, Stupid! On, Late Bloomer And Blitzen!"
line_23 = "To the top of " + random.choice(porch) + "! To the top of the " + random.choice(wall) + "!"
line_24 = "Now " + random.choice(dash_away) + " all!'"

line_25 = "As dry leaves that before the wild hurricane " + random.choice(fly) + ","
line_26 = "When they meet with " + random.choice(an_obstacle) + ", mount to " + random.choice(sky) + ","
line_27 = "So up to the house-top the " + random.choice(coursers) + " they " + random.choice(flew) + ","
line_28 = "With the sleigh full of " + random.choice(toys) + ", and St. Nicholas too."


print(line_1)
print("\t" + line_2)
print("\t" + line_3)
print("\t" + line_4)
print("\t" + line_5)
print("\t" + line_6)
print("\t" + line_7)
print("\t" + line_8)
print(line_9)
print("\t" + line_10)
print("\t" + line_11)
print("\t" + line_12)
print(line_13)
print("\t" + line_14)
print("\t" + line_15)
print("\t" + line_16)
print(line_17)
print("\t" + line_18)
print("\t" + line_19)
print("\t" + line_20)
print(line_21)
print("\t" + line_22)
print("\t" + line_23)
print("\t" + line_24)
print(line_25)
print("\t" + line_26)
print("\t" + line_27)
print("\t" + line_28)